
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Nov 28 20:01:12 CET 2017
//----------------------------------------------------

package pecl;

import java_cup.runtime.*;
import java.io.*;
import java.util.*;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Tue Nov 28 20:01:12 CET 2017
  */
public class PeclCup extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public PeclCup() {super();}

  /** Constructor which sets the default scanner. */
  public PeclCup(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public PeclCup(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\124\000\002\002\004\000\002\002\007\000\002\045" +
    "\003\000\002\004\004\000\002\004\002\000\002\005\007" +
    "\000\002\005\005\000\002\005\003\000\002\010\003\000" +
    "\002\010\005\000\002\010\003\000\002\006\003\000\002" +
    "\006\003\000\002\003\005\000\002\011\004\000\002\011" +
    "\002\000\002\017\005\000\002\017\002\000\002\007\003" +
    "\000\002\007\003\000\002\007\003\000\002\007\003\000" +
    "\002\007\003\000\002\012\005\000\002\012\004\000\002" +
    "\013\003\000\002\013\003\000\002\013\003\000\002\014" +
    "\003\000\002\014\003\000\002\014\006\000\002\016\005" +
    "\000\002\016\005\000\002\016\005\000\002\016\003\000" +
    "\002\015\003\000\002\015\003\000\002\015\003\000\002" +
    "\015\003\000\002\015\003\000\002\015\003\000\002\021" +
    "\003\000\002\021\003\000\002\022\003\000\002\022\006" +
    "\000\002\022\005\000\002\020\003\000\002\023\003\000" +
    "\002\023\003\000\002\035\003\000\002\035\005\000\002" +
    "\024\010\000\002\024\012\000\002\025\003\000\002\026" +
    "\010\000\002\027\005\000\002\027\004\000\002\042\003" +
    "\000\002\042\005\000\002\030\006\000\002\030\007\000" +
    "\002\030\003\000\002\043\003\000\002\043\002\000\002" +
    "\031\003\000\002\031\003\000\002\036\003\000\002\036" +
    "\002\000\002\032\003\000\002\032\003\000\002\032\003" +
    "\000\002\032\003\000\002\033\004\000\002\033\004\000" +
    "\002\034\003\000\002\034\003\000\002\037\003\000\002" +
    "\041\004\000\002\040\004\000\002\040\004\000\002\044" +
    "\003\000\002\044\003\000\002\044\003\000\002\044\003" +
    "" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\207\000\004\004\005\001\002\000\004\002\211\001" +
    "\002\000\004\050\007\001\002\000\004\005\010\001\002" +
    "\000\004\005\uffff\001\002\000\010\003\ufffd\006\ufffd\010" +
    "\ufffd\001\002\000\010\003\014\006\016\010\012\001\002" +
    "\000\006\003\176\050\177\001\002\000\010\003\ufffe\006" +
    "\ufffe\010\ufffe\001\002\000\010\003\ufffa\006\ufffa\010\ufffa" +
    "\001\002\000\004\002\000\001\002\000\022\003\031\007" +
    "\ufff2\013\020\014\032\015\033\016\021\020\027\050\023" +
    "\001\002\000\010\007\uffed\022\uffed\047\uffed\001\002\000" +
    "\004\050\175\001\002\000\012\003\113\027\136\043\135" +
    "\050\114\001\002\000\010\007\uffb0\022\uffb0\047\uffb0\001" +
    "\002\000\004\030\165\001\002\000\010\007\uffec\022\uffec" +
    "\047\uffec\001\002\000\010\007\uffeb\022\uffeb\047\uffeb\001" +
    "\002\000\010\007\uffee\022\uffee\047\uffee\001\002\000\012" +
    "\003\113\027\136\043\135\050\114\001\002\000\010\007" +
    "\ufff0\022\ufff0\047\131\001\002\000\036\003\047\007\uffae" +
    "\022\uffae\025\106\026\107\027\105\037\043\040\055\041" +
    "\051\042\044\043\046\047\uffae\050\101\051\041\001\002" +
    "\000\022\003\047\037\043\040\055\041\051\042\044\043" +
    "\046\050\042\051\041\001\002\000\010\007\uffb5\022\uffb5" +
    "\047\uffb5\001\002\000\010\007\uffef\022\uffef\047\uffef\001" +
    "\002\000\010\007\uffb1\022\uffb1\047\uffb1\001\002\000\004" +
    "\007\040\001\002\000\010\007\uffaf\022\uffaf\047\uffaf\001" +
    "\002\000\004\002\ufff4\001\002\000\042\003\uffb6\007\uffb6" +
    "\017\uffb6\021\uffb6\022\uffb6\023\uffb6\024\uffb6\037\uffb6\040" +
    "\uffb6\041\uffb6\042\uffb6\043\uffb6\044\uffb6\047\uffb6\050\uffb6" +
    "\051\uffb6\001\002\000\020\007\uffb3\022\uffb3\037\uffc1\040" +
    "\uffc1\041\uffc1\042\uffc1\047\uffb3\001\002\000\012\037\uffbd" +
    "\040\uffbd\050\uffbd\051\uffbd\001\002\000\032\003\uffba\007" +
    "\uffba\022\uffba\037\uffba\040\uffba\041\uffba\042\uffba\043\uffba" +
    "\044\uffba\047\uffba\050\uffba\051\uffba\001\002\000\032\003" +
    "\uffc0\007\uffc0\022\uffc0\037\uffc0\040\uffc0\041\uffc0\042\uffc0" +
    "\043\uffc0\044\uffc0\047\uffc0\050\uffc0\051\uffc0\001\002\000" +
    "\020\003\047\037\043\040\055\041\051\042\044\050\065" +
    "\051\041\001\002\000\012\007\uffc4\022\uffc4\044\uffc4\047" +
    "\uffc4\001\002\000\012\037\064\040\063\050\065\051\041" +
    "\001\002\000\032\003\uffbb\007\uffbb\022\uffbb\037\uffbb\040" +
    "\uffbb\041\uffbb\042\uffbb\043\uffbb\044\uffbb\047\uffbb\050\uffbb" +
    "\051\uffbb\001\002\000\012\007\uffc8\022\uffc8\044\uffc8\047" +
    "\uffc8\001\002\000\012\037\062\040\060\041\051\042\044" +
    "\001\002\000\042\003\uffb7\007\uffb7\017\uffb7\021\uffb7\022" +
    "\uffb7\023\uffb7\024\uffb7\037\uffb7\040\uffb7\041\uffb7\042\uffb7" +
    "\043\uffb7\044\uffb7\047\uffb7\050\uffb7\051\uffb7\001\002\000" +
    "\012\037\uffbc\040\uffbc\050\uffbc\051\uffbc\001\002\000\010" +
    "\007\uffb2\022\uffb2\047\uffb2\001\002\000\042\003\uffb8\007" +
    "\uffb8\017\uffb8\021\uffb8\022\uffb8\023\uffb8\024\uffb8\037\uffb8" +
    "\040\uffb8\041\uffb8\042\uffb8\043\uffb8\044\uffb8\047\uffb8\050" +
    "\uffb8\051\uffb8\001\002\000\032\003\uffbc\007\uffbc\022\uffbc" +
    "\037\uffbc\040\uffbc\041\uffbc\042\uffbc\043\uffbc\044\uffbc\047" +
    "\uffbc\050\uffbc\051\uffbc\001\002\000\012\037\064\040\063" +
    "\050\065\051\041\001\002\000\032\003\uffbd\007\uffbd\022" +
    "\uffbd\037\uffbd\040\uffbd\041\uffbd\042\uffbd\043\uffbd\044\uffbd" +
    "\047\uffbd\050\uffbd\051\uffbd\001\002\000\004\051\057\001" +
    "\002\000\004\051\073\001\002\000\032\003\uffc1\007\uffc1" +
    "\022\uffc1\037\uffc1\040\uffc1\041\uffc1\042\uffc1\043\uffc1\044" +
    "\uffc1\047\uffc1\050\uffc1\051\uffc1\001\002\000\032\003\uffbe" +
    "\007\uffbe\022\uffbe\037\062\040\060\041\051\042\044\043" +
    "\uffbe\044\uffbe\047\uffbe\050\uffbe\051\uffbe\001\002\000\032" +
    "\003\uffbf\007\uffbf\022\uffbf\037\uffbf\040\uffbf\041\uffbf\042" +
    "\uffbf\043\uffbf\044\uffbf\047\uffbf\050\uffbf\051\uffbf\001\002" +
    "\000\032\003\047\007\uffc2\022\uffc2\037\043\040\055\041" +
    "\051\042\044\043\046\044\uffc2\047\uffc2\050\065\051\041" +
    "\001\002\000\012\007\uffc5\022\uffc5\044\uffc5\047\uffc5\001" +
    "\002\000\012\007\uffc3\022\uffc3\044\uffc3\047\uffc3\001\002" +
    "\000\042\003\uffb9\007\uffb9\017\uffb9\021\uffb9\022\uffb9\023" +
    "\uffb9\024\uffb9\037\uffb9\040\uffb9\041\uffb9\042\uffb9\043\uffb9" +
    "\044\uffb9\047\uffb9\050\uffb9\051\uffb9\001\002\000\032\003" +
    "\uffbe\007\uffbe\022\uffbe\037\062\040\060\041\051\042\044" +
    "\043\uffbe\044\uffbe\047\uffbe\050\uffbe\051\uffbe\001\002\000" +
    "\032\003\047\007\uffc2\022\uffc2\037\043\040\055\041\051" +
    "\042\044\043\046\044\uffc2\047\uffc2\050\065\051\041\001" +
    "\002\000\012\007\uffc6\022\uffc6\044\uffc6\047\uffc6\001\002" +
    "\000\004\044\100\001\002\000\012\007\uffc7\022\uffc7\044" +
    "\uffc7\047\uffc7\001\002\000\020\007\uffe8\022\uffe8\037\uffc1" +
    "\040\uffc1\041\uffc1\042\uffc1\047\uffe8\001\002\000\010\007" +
    "\uffe6\022\uffe6\047\uffe6\001\002\000\010\007\uffe9\022\uffe9" +
    "\047\uffe9\001\002\000\020\007\uffe7\022\uffe7\037\uffc0\040" +
    "\uffc0\041\uffc0\042\uffc0\047\uffe7\001\002\000\004\043\111" +
    "\001\002\000\022\007\uffe5\017\uffe5\021\uffe5\022\uffe5\023" +
    "\uffe5\024\uffe5\044\uffe5\047\uffe5\001\002\000\022\007\uffe4" +
    "\017\uffe4\021\uffe4\022\uffe4\023\uffe4\024\uffe4\044\uffe4\047" +
    "\uffe4\001\002\000\010\007\uffc9\022\uffc9\047\uffc9\001\002" +
    "\000\006\003\113\050\114\001\002\000\014\017\uffd7\021" +
    "\uffd7\023\uffd7\024\uffd7\044\uffd7\001\002\000\014\017\uffdf" +
    "\021\uffdf\023\uffdf\024\uffdf\044\uffdf\001\002\000\030\017" +
    "\uffd8\021\uffd8\023\uffd8\024\uffd8\031\123\032\122\033\120" +
    "\034\124\035\125\036\121\044\uffd8\001\002\000\004\044" +
    "\116\001\002\000\022\007\uffe3\017\uffe3\021\uffe3\022\uffe3" +
    "\023\uffe3\024\uffe3\044\uffe3\047\uffe3\001\002\000\012\037" +
    "\064\040\063\050\130\051\041\001\002\000\020\025\106" +
    "\026\107\027\105\037\uffdc\040\uffdc\050\uffdc\051\uffdc\001" +
    "\002\000\012\037\uffd9\040\uffd9\050\uffd9\051\uffd9\001\002" +
    "\000\012\037\uffdd\040\uffdd\050\uffdd\051\uffdd\001\002\000" +
    "\012\037\uffde\040\uffde\050\uffde\051\uffde\001\002\000\012" +
    "\037\uffdb\040\uffdb\050\uffdb\051\uffdb\001\002\000\012\037" +
    "\uffda\040\uffda\050\uffda\051\uffda\001\002\000\014\017\uffe0" +
    "\021\uffe0\023\uffe0\024\uffe0\044\uffe0\001\002\000\014\017" +
    "\uffe1\021\uffe1\023\uffe1\024\uffe1\044\uffe1\001\002\000\014" +
    "\017\uffe2\021\uffe2\023\uffe2\024\uffe2\044\uffe2\001\002\000" +
    "\020\003\031\013\020\014\032\015\033\016\021\020\027" +
    "\050\023\001\002\000\006\007\ufff3\022\ufff3\001\002\000" +
    "\010\007\ufff0\022\ufff0\047\131\001\002\000\006\007\ufff1" +
    "\022\ufff1\001\002\000\010\003\113\027\136\050\114\001" +
    "\002\000\004\043\160\001\002\000\004\021\147\001\002" +
    "\000\014\017\uffd6\021\uffd6\023\uffd6\024\uffd6\044\uffd6\001" +
    "\002\000\012\017\uffd0\021\uffd0\023\142\024\144\001\002" +
    "\000\010\003\uffd2\027\uffd2\050\uffd2\001\002\000\010\003" +
    "\113\027\136\050\114\001\002\000\010\003\uffd1\027\uffd1" +
    "\050\uffd1\001\002\000\014\017\uffd4\021\uffd4\023\uffd4\024" +
    "\uffd4\044\uffd4\001\002\000\014\017\uffd3\021\uffd3\023\142" +
    "\024\144\044\uffd3\001\002\000\024\003\031\007\ufff2\013" +
    "\020\014\032\015\033\016\021\020\027\022\ufff2\050\023" +
    "\001\002\000\006\007\156\022\uffcc\001\002\000\004\022" +
    "\152\001\002\000\022\003\031\007\ufff2\013\020\014\032" +
    "\015\033\016\021\020\027\050\023\001\002\000\004\007" +
    "\154\001\002\000\004\020\155\001\002\000\010\007\uffcd" +
    "\022\uffcd\047\uffcd\001\002\000\004\020\157\001\002\000" +
    "\010\007\uffce\022\uffce\047\uffce\001\002\000\010\003\113" +
    "\027\136\050\114\001\002\000\010\023\142\024\144\044" +
    "\162\001\002\000\014\017\uffd5\021\uffd5\023\uffd5\024\uffd5" +
    "\044\uffd5\001\002\000\010\023\142\024\144\044\164\001" +
    "\002\000\006\017\uffcf\021\uffcf\001\002\000\030\003\047" +
    "\025\106\026\107\027\105\037\043\040\055\041\051\042" +
    "\044\043\046\050\101\051\041\001\002\000\010\007\uffea" +
    "\022\uffea\047\uffea\001\002\000\010\007\uffca\022\uffca\047" +
    "\uffca\001\002\000\004\017\171\001\002\000\022\003\031" +
    "\007\ufff2\013\020\014\032\015\033\016\021\020\027\050" +
    "\023\001\002\000\004\007\173\001\002\000\004\016\174" +
    "\001\002\000\010\007\uffcb\022\uffcb\047\uffcb\001\002\000" +
    "\010\007\uffb4\022\uffb4\047\uffb4\001\002\000\010\045\ufff7" +
    "\046\ufff7\047\ufff7\001\002\000\010\045\ufff9\046\ufff9\047" +
    "\ufff9\001\002\000\010\045\201\046\203\047\202\001\002" +
    "\000\004\050\210\001\002\000\010\003\ufffb\006\ufffb\010" +
    "\ufffb\001\002\000\006\011\204\012\206\001\002\000\004" +
    "\047\ufff6\001\002\000\004\047\207\001\002\000\004\047" +
    "\ufff5\001\002\000\010\003\ufffc\006\ufffc\010\ufffc\001\002" +
    "\000\010\045\ufff8\046\ufff8\047\ufff8\001\002\000\004\002" +
    "\001\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\207\000\004\002\003\001\001\000\002\001\001\000" +
    "\004\045\005\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\004\010\001\001\000\006\003\014\005\012\001" +
    "\001\000\004\010\177\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\026\007\027\011\035\012" +
    "\025\024\016\026\023\027\033\037\034\040\036\041\021" +
    "\044\024\001\001\000\002\001\001\000\002\001\001\000" +
    "\012\016\111\021\137\022\140\035\167\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\012\016\111\021\137\022\140" +
    "\035\136\001\001\000\004\017\131\001\001\000\022\013" +
    "\102\014\101\030\051\031\052\032\047\033\053\034\103" +
    "\042\107\001\001\000\016\030\051\031\052\032\047\033" +
    "\053\034\044\042\055\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\014\030\076\031\052\032\047\033\053\034\044\001\001" +
    "\000\002\001\001\000\010\031\073\033\053\034\044\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\032\060" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\010\031\065" +
    "\033\053\034\044\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\006\032\066" +
    "\036\067\001\001\000\002\001\001\000\020\030\051\031" +
    "\052\032\047\033\053\034\044\042\071\043\070\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\006\032\066\036\074\001\001\000\020\030\051\031\052" +
    "\032\047\033\053\034\044\042\071\043\075\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\006\016\111\021\114\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\015\116\001\001" +
    "\000\002\001\001\000\002\001\001\000\006\033\053\034" +
    "\126\001\001\000\004\014\125\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\024\007\132\012\025\024\016\026\023\027" +
    "\033\037\034\040\036\041\021\044\024\001\001\000\002" +
    "\001\001\000\004\017\133\001\001\000\002\001\001\000" +
    "\010\016\111\021\137\022\162\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\023\142\001" +
    "\001\000\002\001\001\000\012\016\111\020\144\021\137" +
    "\022\145\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\023\142\001\001\000\030\007\027\011\147\012\025" +
    "\024\016\025\150\026\023\027\033\037\034\040\036\041" +
    "\021\044\024\001\001\000\002\001\001\000\002\001\001" +
    "\000\026\007\027\011\152\012\025\024\016\026\023\027" +
    "\033\037\034\040\036\041\021\044\024\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\010\016\111\021\137\022\160" +
    "\001\001\000\004\023\142\001\001\000\002\001\001\000" +
    "\004\023\142\001\001\000\002\001\001\000\022\013\165" +
    "\014\101\030\051\031\052\032\047\033\053\034\103\042" +
    "\166\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\026\007\027\011\171\012\025\024\016\026" +
    "\023\027\033\037\034\040\036\041\021\044\024\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\006" +
    "\204\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$PeclCup$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$PeclCup$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$PeclCup$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



public static void main (String argc[]) throws Exception{
   String extension="";
   String programa=argc[0]; 
   
   for (int i=programa.length()-5;i<programa.length();i++){
   		extension=extension+programa.charAt(i);
   }
  if(extension.equals(".prog")){
     	FileInputStream prog=new FileInputStream(programa);
     	Yylex y=new Yylex(prog);
   		PeclCup principal=new PeclCup(y);
   		principal.parse();
   		System.out.println("ANALIZADOR LEXICO");
   		System.out.println(y.imprimir());
   		System.out.println("\nNumero de errorres lexicos: "+ y.getErr()+"\n");
   		
  }
  else{
  	System.err.println("ERROR. EL ARCHIVO DEBE DE SER .prog");
  }
}  
public void syntax_error(Symbol s) {
  System.err.println("Error de sintaxis linea " +(s.left+1)+" en o cerca de "+s.value);
 
 
}  
public void report_fatal_error(String message, Object info) {
  done_parsing();
  report_error("Error de sintaxis fatal : "
  + "No se puede recuperar del error y continuar con el analisis - "
  + message + " ",(Symbol)info);
  report_error("** Final del analisis.", null);
  System.exit(1);
}
  

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$PeclCup$actions {


Hashtable<String,Simbolo> tSimbolos=new Hashtable<String, Simbolo>();
ArrayList<String> lvariables = new ArrayList<String>();
Arbol a;
Nodo aux;
Nodo aux1;
Nodo aux2;
Nodo aux3;
Nodo aux4;
Nodo raiz;
boolean ifwhile;
StringBuffer sif =new StringBuffer();
StringBuffer sfin =new StringBuffer();
int numErr=0;
int numErrS=0;
String tipo;

public void añadeHojaDecl (){
for (int i=0;i<lvariables.size();i++){
	aux.añadirHijo(new NodoHoja(lvariables.get(i),""));

	}
}

public String impTDS(){
String s="";
s+="NOMBRE\t\tTIPO\t\tINICIALIZADO\n";
Enumeration e=tSimbolos.keys();
	while(e.hasMoreElements()){
	String c= e.nextElement().toString();
	Simbolo sim=tSimbolos.get(c);
	if(sim.getTipo().equals("undefined")){
	s+=c+"\t\t"+sim.getTipo()+"\t"+sim.getValor()+"\n";
	}
	else{
	s+=c+"\t\t"+sim.getTipo()+"\t\t"+sim.getValor()+"\n";
	}
	}

return s;
}

public void añadeExpresion()  {
if (ifwhile){
	aux.añadirHijo(aux1);

}
else{
	raiz.añadirHijo(aux1);
}

}
public boolean estaTabla(String s){
if (tSimbolos.containsKey(s)) return true;
else return false;
}
public void compruebaIntBool(Object o, int num){
	if(!estaTabla(o.toString())) System.err.println("Error semantico en la linea "+num+". La variable "+o.toString()+" no esta defninida");
	else if(tSimbolos.get(o.toString()).getTipo().equals("pseudo")){
	System.err.println("Error semantico en la linea "+num+". La variable "+o.toString()+" es el nombre del programa, no puede ser usado como variable");
	numErrS++;
	}
	else {
		Simbolo uno= tSimbolos.get(o.toString());
	    String un =uno.getTipo();		
		if(!un.equals("boolean") && !un.equals("integer")){
			System.err.println("Error semantico en la linea "+num+". La variable "+o.toString()+" debe ser un boolean o integer");
			numErrS++;
		}
		else if(!tSimbolos.get(o.toString()).getValor()){
		System.err.println("Error semantico en la linea "+num+". La variable "+o.toString()+" no esta inicializada");
		numErrS++;
		}
	
	}



}
public void compruebaBool(Object o, int num){
	if(!estaTabla(o.toString())) System.err.println("Error semantico en la linea "+num+". La variable "+o.toString()+" no esta defninida");
	else if(tSimbolos.get(o.toString()).getTipo().equals("pseudo")){
	System.err.println("Error semantico en la linea "+num+". La variable "+o.toString()+" es el nombre del programa, no puede ser usado como variable");
	numErrS++;
	}
	else {
		Simbolo uno= tSimbolos.get(o.toString());
	    String un =uno.getTipo();		
		if(un.equals("undefined")){
			uno.setTipo("boolean");
		}
		else if(!tSimbolos.get(o.toString()).getValor()){
		System.err.println("Error semantico en la linea "+num+". La variable "+o.toString()+" no esta inicializada");
		numErrS++;
		}
		else if(!un.equals("boolean")){
			System.err.println("Error semantico en la linea "+num+". La variable "+o.toString()+" debe ser  boolean");
		}
	
	}
	
}

public void compruebaInt(Object o, int num){
	if(!estaTabla(o.toString())) System.err.println("Error semantico en la linea "+num+". La variable "+o.toString()+" no esta defninida");
	else if(tSimbolos.get(o.toString()).getTipo().equals("pseudo")){
	System.err.println("La variable "+o.toString()+" es el nombre del programa, no puede ser usado como variable");
	numErrS++;
	}
	else {
		Simbolo uno= tSimbolos.get(o.toString());
	    String un =uno.getTipo();		
		if(un.equals("undefined")){
			uno.setTipo("integer");
		}
		else if(!tSimbolos.get(o.toString()).getValor()){
		System.err.println("Error semantico en la linea "+num+". La variable "+o.toString()+" no esta inicializada");
		numErrS++;
		}
		else if(!un.equals("integer")){
			System.err.println("Error semantico en la linea "+num+". La variable "+o.toString()+" debe ser un entero");
		}
	
	}
	
}

public void compruebaIntAsig(Object o, int num){
	if(!estaTabla(o.toString())) System.err.println("Error semantico en la linea "+num+". La variable "+o.toString()+" no esta defninida");
	else if(tSimbolos.get(o.toString()).getTipo().equals("pseudo")){
	System.err.println("La variable "+o.toString()+" es el nombre del programa, no puede ser usado como variable");
	numErrS++;
	}
	else {
		Simbolo uno= tSimbolos.get(o.toString());
	    String un =uno.getTipo();		
		if(un.equals("undefined")){
			uno.setTipo("integer");
		}
		else if(!un.equals("integer")){
			System.err.println("Error semantico en la linea "+num+". La variable "+o.toString()+" debe ser un entero");
		}
	
	}
	
}
public void compruebaVariable(Object a, Object b, int num){
if(!estaTabla(a.toString())) System.err.println("La variable "+a.toString()+" no esta defninida");
else if(tSimbolos.get(a.toString()).getTipo().equals("pseudo")){
	System.err.println("Error semantico en la linea "+num+". La variable "+a.toString()+" es el nombre del programa, no puede ser usado como variable");
	numErrS++;
}
else if(b.toString()=="integer" || b.toString()=="boolean"){


		Simbolo uno= tSimbolos.get(a.toString());
	    String un =uno.getTipo();		
		if(!un.equals(b.toString())){
		System.err.println("Error semantico en la linea "+num+". La variable "+a.toString()+" no es compatible con "+b.toString());
		numErrS++;
		}
		else if(!tSimbolos.get(a.toString()).getValor()){
		System.err.println("Error semantico en la linea "+num+". La variable "+a.toString()+" no esta inicializada");
		numErrS++;
 
 }
	
}	
else{ 	
	 	if(!estaTabla(b.toString())){ System.err.println("Error semantico en la linea "+num+". La variable "+b+" no esta defninida");
	 	numErr++;
		}
		else{ 
		Simbolo uno= tSimbolos.get(a.toString());
		Simbolo dos= tSimbolos.get(b.toString());
		String un =uno.getTipo();
		String dop =dos.getTipo();
		if(un.equals("undefined")){
			uno.setTipo(dop);
		}
		else if(!un.equals(dop)){
		System.err.println("Error semantico en la linea "+num+". La variable "+a.toString()+" no es compatible con "+b.toString());
		numErrS++;
		}
		else{ if(!tSimbolos.get(a.toString()).getValor()){
		System.err.println("Error semantico en la linea "+num+". La variable "+a.toString()+" no esta inicializada");
		numErrS++;
		}
		if(!tSimbolos.get(b.toString()).getValor()){
		System.err.println("Error semantico en la linea "+num+". La variable "+b.toString()+" no esta inicializada");
		numErrS++;
        	}
    	} 
       }	   
	}    
}

public void compruebaVariableAsig(Object a, Object b, int num){
if(!estaTabla(a.toString())) System.err.println("La variable "+a.toString()+" no esta defninida");
else if(tSimbolos.get(a.toString()).getTipo().equals("pseudo")){
	System.err.println("Error semantico en la linea "+num+". La variable "+a.toString()+" es el nombre del programa, no puede ser usado como variable");
	numErrS++;
	
}
else if(b.toString()=="integer" || b.toString()=="boolean"){


		Simbolo uno= tSimbolos.get(a.toString());
	    String un =uno.getTipo();	
	    if(un.equals("undefined")){
			uno.setTipo(b.toString());
			uno.inicializar();
		}	
		else if(!un.equals(b.toString())){
		System.err.println("Error semantico en la linea "+num+". La variable "+a.toString()+" no es compatible con "+b.toString());
		numErrS++;
		}
		else{
		uno.inicializar();
		}
 
 }
	
	
else{ 	
	 	if(!estaTabla(b.toString())){ System.err.println("Error semantico en la linea "+num+". La variable "+b+" no esta defninida");
	 	numErrS++;
		}
		else{
		Simbolo uno= tSimbolos.get(a.toString());
		Simbolo dos= tSimbolos.get(b.toString());
		String un =uno.getTipo();
		String dop =dos.getTipo();
		if(un.equals("undefined")){
			uno.setTipo(dop);
			if(dop.equals("undefined")){
			System.err.println("Error semantico en la linea "+num+". La variable "+b.toString()+" no esta definido");
			numErrS++;
			}
			else if(!dos.getValor()){
			System.err.println("Error semantico en la linea "+num+". La variable "+b.toString()+" no esta inicializada");
			}
			else{
			uno.inicializar();
			}
		
		}
		else if(!un.equals(dop)){
		System.err.println("Error semantico en la linea "+num+". La variable "+a.toString()+" no es compatible con "+b.toString());
		numErrS++;
		}
		else if(!tSimbolos.get(b.toString()).getValor()){
		System.err.println("Error semantico en la linea "+num+". La variable "+b.toString()+" no esta inicializada");
		numErrS++;
		}
		else{
		
		uno.inicializar();
		}
		}
        
    }    
	    
}


public void añadirArray(String a, int b){
	if(lvariables.contains(a)){
		System.err.println("Error semantico en linea "+b+ ". El caracter "+a+" ya esta definido");
		numErrS++;
	}
	else{
	lvariables.add(a);	
	}
}
public void añadirVariables( Object b, int a){

 while (!lvariables.isEmpty()){
 			if(estaTabla(lvariables.get(0))){
 			 System.err.println("Error semantico en linea "+a+ ". El caracter "+lvariables.get(0)+" ya esta definido");
 			 numErrS++;
 			 lvariables.remove(0);
 			 }
 			
 			else{
            tSimbolos.put(lvariables.get(0), new Simbolo(b.toString()));
            lvariables.remove(0);
            }
        }


}

public void añadirVariablesUnd(int a){

 while (!lvariables.isEmpty()){
 			if(estaTabla(lvariables.get(0))){
 			 System.err.println("Error semantico en linea "+a+ ". El caracter "+lvariables.get(0)+" ya esta definido");
 			 numErrS++;
 			 lvariables.remove(0);
 			 }
 			
 			else{
            tSimbolos.put(lvariables.get(0), new Simbolo("undefined"));
            lvariables.remove(0);
            }
        }


}

public void inicializar(Object o){
	tSimbolos.get(o.toString()).inicializar();
}
public void meterSimbolo(String s, Simbolo sim){
tSimbolos.put(s, sim);
}

public void fin(){
	sfin.append("\n....ANALISIS FINALIZADO .....\n");
	sfin.append("Numero de errores sintacticos: "+numErr+"\n");
	sfin.append("Numero de errores semanticos: "+numErrS+"\n");
	
	if(numErr==0 && numErrS==0){
		sfin.append("TABLA DE SIMBOLOS: \n");
		sfin.append(impTDS()); sfin.append("\n");
		sfin.append("ARBOL SINTACTICO: \n");
		sfin.append(a.imprimir());
	}
	System.out.println(sfin.toString());
}


  private final PeclCup parser;

  /** Constructor */
  CUP$PeclCup$actions(PeclCup parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$PeclCup$do_action(
    int                        CUP$PeclCup$act_num,
    java_cup.runtime.lr_parser CUP$PeclCup$parser,
    java.util.Stack            CUP$PeclCup$stack,
    int                        CUP$PeclCup$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$PeclCup$result;

      /* select the action based on the action number */
      switch (CUP$PeclCup$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 83: // expresion2 ::= error 
            {
              Object RESULT =null;
		numErr++;
              CUP$PeclCup$result = parser.getSymbolFactory().newSymbol("expresion2",34, ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), RESULT);
            }
          return CUP$PeclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 82: // expresion2 ::= write 
            {
              Object RESULT =null;
		 aux1=new NodoIntermedio("write"); aux1.añadirHijo(aux); añadeExpresion();
              CUP$PeclCup$result = parser.getSymbolFactory().newSymbol("expresion2",34, ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), RESULT);
            }
          return CUP$PeclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 81: // expresion2 ::= read 
            {
              Object RESULT =null;
		 aux1=new NodoIntermedio("read");  aux1.añadirHijo(aux); añadeExpresion();
              CUP$PeclCup$result = parser.getSymbolFactory().newSymbol("expresion2",34, ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), RESULT);
            }
          return CUP$PeclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 80: // expresion2 ::= skip 
            {
              Object RESULT =null;
		 aux1=new NodoIntermedio("skip"); aux1.añadirHijo(aux); añadeExpresion();
              CUP$PeclCup$result = parser.getSymbolFactory().newSymbol("expresion2",34, ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), RESULT);
            }
          return CUP$PeclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 79: // write ::= WRITE opcion 
            {
              Object RESULT =null;
		aux=new NodoIntermedio("Operation"); aux.añadirHijo(aux3); 
              CUP$PeclCup$result = parser.getSymbolFactory().newSymbol("write",30, ((java_cup.runtime.Symbol)CUP$PeclCup$stack.elementAt(CUP$PeclCup$top-1)), ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), RESULT);
            }
          return CUP$PeclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 78: // write ::= WRITE IDE 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$PeclCup$stack.peek()).value;
		 compruebaIntBool(id, idleft+1);  aux=new NodoHoja("IDE",id.toString()); 
              CUP$PeclCup$result = parser.getSymbolFactory().newSymbol("write",30, ((java_cup.runtime.Symbol)CUP$PeclCup$stack.elementAt(CUP$PeclCup$top-1)), ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), RESULT);
            }
          return CUP$PeclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 77: // read ::= READ IDE 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$PeclCup$stack.peek()).value;
		compruebaInt(id, idleft+1);  aux=new NodoHoja("IDE",id.toString()); 
              CUP$PeclCup$result = parser.getSymbolFactory().newSymbol("read",31, ((java_cup.runtime.Symbol)CUP$PeclCup$stack.elementAt(CUP$PeclCup$top-1)), ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), RESULT);
            }
          return CUP$PeclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 76: // skip ::= SKIP 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$PeclCup$stack.peek()).value;
		aux=new NodoHoja("","");
              CUP$PeclCup$result = parser.getSymbolFactory().newSymbol("skip",29, ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), RESULT);
            }
          return CUP$PeclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 75: // numero ::= NUM 
            {
              Object RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()).right;
		Object n = (Object)((java_cup.runtime.Symbol) CUP$PeclCup$stack.peek()).value;
		 RESULT=n;
              CUP$PeclCup$result = parser.getSymbolFactory().newSymbol("numero",26, ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), RESULT);
            }
          return CUP$PeclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 74: // numero ::= conSigno 
            {
              Object RESULT =null;
		
              CUP$PeclCup$result = parser.getSymbolFactory().newSymbol("numero",26, ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), RESULT);
            }
          return CUP$PeclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 73: // conSigno ::= RESTA NUM 
            {
              Object RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()).right;
		Object n = (Object)((java_cup.runtime.Symbol) CUP$PeclCup$stack.peek()).value;
		RESULT="-"+n.toString();
              CUP$PeclCup$result = parser.getSymbolFactory().newSymbol("conSigno",25, ((java_cup.runtime.Symbol)CUP$PeclCup$stack.elementAt(CUP$PeclCup$top-1)), ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), RESULT);
            }
          return CUP$PeclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 72: // conSigno ::= SUMA NUM 
            {
              Object RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()).right;
		Object n = (Object)((java_cup.runtime.Symbol) CUP$PeclCup$stack.peek()).value;
		RESULT="+"+n.toString();
              CUP$PeclCup$result = parser.getSymbolFactory().newSymbol("conSigno",25, ((java_cup.runtime.Symbol)CUP$PeclCup$stack.elementAt(CUP$PeclCup$top-1)), ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), RESULT);
            }
          return CUP$PeclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 71: // operador ::= MULTIPLICACION 
            {
              Object RESULT =null;
		RESULT="*";
              CUP$PeclCup$result = parser.getSymbolFactory().newSymbol("operador",24, ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), RESULT);
            }
          return CUP$PeclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 70: // operador ::= DIVISION 
            {
              Object RESULT =null;
		RESULT="/";
              CUP$PeclCup$result = parser.getSymbolFactory().newSymbol("operador",24, ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), RESULT);
            }
          return CUP$PeclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 69: // operador ::= RESTA 
            {
              Object RESULT =null;
		RESULT="-";
              CUP$PeclCup$result = parser.getSymbolFactory().newSymbol("operador",24, ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), RESULT);
            }
          return CUP$PeclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // operador ::= SUMA 
            {
              Object RESULT =null;
		RESULT="+";
              CUP$PeclCup$result = parser.getSymbolFactory().newSymbol("operador",24, ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), RESULT);
            }
          return CUP$PeclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // operadorParent ::= 
            {
              Object RESULT =null;
		RESULT="";
              CUP$PeclCup$result = parser.getSymbolFactory().newSymbol("operadorParent",28, ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), RESULT);
            }
          return CUP$PeclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // operadorParent ::= operador 
            {
              Object RESULT =null;
		int oleft = ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()).left;
		int oright = ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()).right;
		Object o = (Object)((java_cup.runtime.Symbol) CUP$PeclCup$stack.peek()).value;
		RESULT=o;
              CUP$PeclCup$result = parser.getSymbolFactory().newSymbol("operadorParent",28, ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), RESULT);
            }
          return CUP$PeclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // operando ::= numero 
            {
              Object RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()).right;
		Object n = (Object)((java_cup.runtime.Symbol) CUP$PeclCup$stack.peek()).value;
		RESULT=n.toString();
              CUP$PeclCup$result = parser.getSymbolFactory().newSymbol("operando",23, ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), RESULT);
            }
          return CUP$PeclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // operando ::= IDE 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$PeclCup$stack.peek()).value;
		compruebaInt(id, idleft+1); RESULT=id.toString();
              CUP$PeclCup$result = parser.getSymbolFactory().newSymbol("operando",23, ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), RESULT);
            }
          return CUP$PeclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // opcion2 ::= 
            {
              Object RESULT =null;
		RESULT="";
              CUP$PeclCup$result = parser.getSymbolFactory().newSymbol("opcion2",33, ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), RESULT);
            }
          return CUP$PeclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // opcion2 ::= opcion 
            {
              Object RESULT =null;
		int oleft = ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()).left;
		int oright = ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()).right;
		Object o = (Object)((java_cup.runtime.Symbol) CUP$PeclCup$stack.peek()).value;
		RESULT=o;
              CUP$PeclCup$result = parser.getSymbolFactory().newSymbol("opcion2",33, ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), RESULT);
            }
          return CUP$PeclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // operaciones ::= error 
            {
              Object RESULT =null;
		numErr++;
              CUP$PeclCup$result = parser.getSymbolFactory().newSymbol("operaciones",22, ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), RESULT);
            }
          return CUP$PeclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // operaciones ::= operando operador operando operadorParent opcion2 
            {
              Object RESULT =null;
		int o1left = ((java_cup.runtime.Symbol)CUP$PeclCup$stack.elementAt(CUP$PeclCup$top-4)).left;
		int o1right = ((java_cup.runtime.Symbol)CUP$PeclCup$stack.elementAt(CUP$PeclCup$top-4)).right;
		Object o1 = (Object)((java_cup.runtime.Symbol) CUP$PeclCup$stack.elementAt(CUP$PeclCup$top-4)).value;
		int oleft = ((java_cup.runtime.Symbol)CUP$PeclCup$stack.elementAt(CUP$PeclCup$top-3)).left;
		int oright = ((java_cup.runtime.Symbol)CUP$PeclCup$stack.elementAt(CUP$PeclCup$top-3)).right;
		Object o = (Object)((java_cup.runtime.Symbol) CUP$PeclCup$stack.elementAt(CUP$PeclCup$top-3)).value;
		int o2left = ((java_cup.runtime.Symbol)CUP$PeclCup$stack.elementAt(CUP$PeclCup$top-2)).left;
		int o2right = ((java_cup.runtime.Symbol)CUP$PeclCup$stack.elementAt(CUP$PeclCup$top-2)).right;
		Object o2 = (Object)((java_cup.runtime.Symbol) CUP$PeclCup$stack.elementAt(CUP$PeclCup$top-2)).value;
		int opaleft = ((java_cup.runtime.Symbol)CUP$PeclCup$stack.elementAt(CUP$PeclCup$top-1)).left;
		int oparight = ((java_cup.runtime.Symbol)CUP$PeclCup$stack.elementAt(CUP$PeclCup$top-1)).right;
		Object opa = (Object)((java_cup.runtime.Symbol) CUP$PeclCup$stack.elementAt(CUP$PeclCup$top-1)).value;
		int op2left = ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()).left;
		int op2right = ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()).right;
		Object op2 = (Object)((java_cup.runtime.Symbol) CUP$PeclCup$stack.peek()).value;
		aux2 = new NodoHoja("op",o1+""+o+""+o2+""+opa+""+o2); String s=o1+""+o+""+o2+""+opa+""+o2; RESULT=s;
              CUP$PeclCup$result = parser.getSymbolFactory().newSymbol("operaciones",22, ((java_cup.runtime.Symbol)CUP$PeclCup$stack.elementAt(CUP$PeclCup$top-4)), ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), RESULT);
            }
          return CUP$PeclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // operaciones ::= operador operando operadorParent opcion2 
            {
              Object RESULT =null;
		int oleft = ((java_cup.runtime.Symbol)CUP$PeclCup$stack.elementAt(CUP$PeclCup$top-3)).left;
		int oright = ((java_cup.runtime.Symbol)CUP$PeclCup$stack.elementAt(CUP$PeclCup$top-3)).right;
		Object o = (Object)((java_cup.runtime.Symbol) CUP$PeclCup$stack.elementAt(CUP$PeclCup$top-3)).value;
		int opleft = ((java_cup.runtime.Symbol)CUP$PeclCup$stack.elementAt(CUP$PeclCup$top-2)).left;
		int opright = ((java_cup.runtime.Symbol)CUP$PeclCup$stack.elementAt(CUP$PeclCup$top-2)).right;
		Object op = (Object)((java_cup.runtime.Symbol) CUP$PeclCup$stack.elementAt(CUP$PeclCup$top-2)).value;
		int opaleft = ((java_cup.runtime.Symbol)CUP$PeclCup$stack.elementAt(CUP$PeclCup$top-1)).left;
		int oparight = ((java_cup.runtime.Symbol)CUP$PeclCup$stack.elementAt(CUP$PeclCup$top-1)).right;
		Object opa = (Object)((java_cup.runtime.Symbol) CUP$PeclCup$stack.elementAt(CUP$PeclCup$top-1)).value;
		int o2left = ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()).left;
		int o2right = ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()).right;
		Object o2 = (Object)((java_cup.runtime.Symbol) CUP$PeclCup$stack.peek()).value;
		aux2 = new NodoHoja("op",o+""+op+""+opa+""+o2);String s=o+""+op+""+opa+""+o2; RESULT=s;
              CUP$PeclCup$result = parser.getSymbolFactory().newSymbol("operaciones",22, ((java_cup.runtime.Symbol)CUP$PeclCup$stack.elementAt(CUP$PeclCup$top-3)), ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), RESULT);
            }
          return CUP$PeclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // opcion ::= PARENT_IZQ operaciones PARENT_DER 
            {
              Object RESULT =null;
		aux3=new NodoIntermedio("PARENT"); aux3.añadirHijo(aux2); 
              CUP$PeclCup$result = parser.getSymbolFactory().newSymbol("opcion",32, ((java_cup.runtime.Symbol)CUP$PeclCup$stack.elementAt(CUP$PeclCup$top-2)), ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), RESULT);
            }
          return CUP$PeclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // opcion ::= operaciones 
            {
              Object RESULT =null;
		aux3=new NodoIntermedio("NO_PARENT"); aux3.añadirHijo(aux2); 
              CUP$PeclCup$result = parser.getSymbolFactory().newSymbol("opcion",32, ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), RESULT);
            }
          return CUP$PeclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // operacion ::= error opcion 
            {
              Object RESULT =null;

              CUP$PeclCup$result = parser.getSymbolFactory().newSymbol("operacion",21, ((java_cup.runtime.Symbol)CUP$PeclCup$stack.elementAt(CUP$PeclCup$top-1)), ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), RESULT);
            }
          return CUP$PeclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // operacion ::= IDE ASIGNACION opcion 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$PeclCup$stack.elementAt(CUP$PeclCup$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$PeclCup$stack.elementAt(CUP$PeclCup$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$PeclCup$stack.elementAt(CUP$PeclCup$top-2)).value;
		int asleft = ((java_cup.runtime.Symbol)CUP$PeclCup$stack.elementAt(CUP$PeclCup$top-1)).left;
		int asright = ((java_cup.runtime.Symbol)CUP$PeclCup$stack.elementAt(CUP$PeclCup$top-1)).right;
		String as = (String)((java_cup.runtime.Symbol) CUP$PeclCup$stack.elementAt(CUP$PeclCup$top-1)).value;
		int oleft = ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()).left;
		int oright = ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()).right;
		Object o = (Object)((java_cup.runtime.Symbol) CUP$PeclCup$stack.peek()).value;
		 compruebaIntAsig(id, idleft+1); inicializar(id); aux = new NodoIntermedio(id.toString()); aux.añadirHijo(aux3); 
              CUP$PeclCup$result = parser.getSymbolFactory().newSymbol("operacion",21, ((java_cup.runtime.Symbol)CUP$PeclCup$stack.elementAt(CUP$PeclCup$top-2)), ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), RESULT);
            }
          return CUP$PeclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // while ::= WHILE parentExLogica DO sentencias END WHILE 
            {
              Object RESULT =null;
		aux=new NodoIntermedio("IF"); aux.añadirHijo(aux4); ifwhile=false; 
              CUP$PeclCup$result = parser.getSymbolFactory().newSymbol("while",20, ((java_cup.runtime.Symbol)CUP$PeclCup$stack.elementAt(CUP$PeclCup$top-5)), ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), RESULT);
            }
          return CUP$PeclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // else ::= sentencias 
            {
              Object RESULT =null;

              CUP$PeclCup$result = parser.getSymbolFactory().newSymbol("else",19, ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), RESULT);
            }
          return CUP$PeclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // if ::= IF parentExLogica THEN else ELSE sentencias END IF 
            {
              Object RESULT =null;
		aux=new NodoIntermedio("IF-ELSE"); aux.añadirHijo(aux4); 
              CUP$PeclCup$result = parser.getSymbolFactory().newSymbol("if",18, ((java_cup.runtime.Symbol)CUP$PeclCup$stack.elementAt(CUP$PeclCup$top-7)), ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), RESULT);
            }
          return CUP$PeclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // if ::= IF parentExLogica THEN sentencias END IF 
            {
              Object RESULT =null;
		aux=new NodoIntermedio("IF"); aux.añadirHijo(aux4);  
              CUP$PeclCup$result = parser.getSymbolFactory().newSymbol("if",18, ((java_cup.runtime.Symbol)CUP$PeclCup$stack.elementAt(CUP$PeclCup$top-5)), ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), RESULT);
            }
          return CUP$PeclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // parentExLogica ::= PARENT_IZQ exLogicas PARENT_DER 
            {
              Object RESULT =null;

              CUP$PeclCup$result = parser.getSymbolFactory().newSymbol("parentExLogica",27, ((java_cup.runtime.Symbol)CUP$PeclCup$stack.elementAt(CUP$PeclCup$top-2)), ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), RESULT);
            }
          return CUP$PeclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // parentExLogica ::= exLogicas 
            {
              Object RESULT =null;

              CUP$PeclCup$result = parser.getSymbolFactory().newSymbol("parentExLogica",27, ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), RESULT);
            }
          return CUP$PeclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // tLogica ::= OR 
            {
              Object RESULT =null;
		sif.append(" or ");
              CUP$PeclCup$result = parser.getSymbolFactory().newSymbol("tLogica",17, ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), RESULT);
            }
          return CUP$PeclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // tLogica ::= AND 
            {
              Object RESULT =null;
		sif.append(" and ");
              CUP$PeclCup$result = parser.getSymbolFactory().newSymbol("tLogica",17, ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), RESULT);
            }
          return CUP$PeclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // otra ::= exLogicas 
            {
              Object RESULT =null;

              CUP$PeclCup$result = parser.getSymbolFactory().newSymbol("otra",14, ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), RESULT);
            }
          return CUP$PeclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // exLogicas ::= exLogicas tLogica otra 
            {
              Object RESULT =null;

              CUP$PeclCup$result = parser.getSymbolFactory().newSymbol("exLogicas",16, ((java_cup.runtime.Symbol)CUP$PeclCup$stack.elementAt(CUP$PeclCup$top-2)), ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), RESULT);
            }
          return CUP$PeclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // exLogicas ::= NOT PARENT_IZQ exLogicas PARENT_DER 
            {
              Object RESULT =null;
		sif.append("Neg");  
              CUP$PeclCup$result = parser.getSymbolFactory().newSymbol("exLogicas",16, ((java_cup.runtime.Symbol)CUP$PeclCup$stack.elementAt(CUP$PeclCup$top-3)), ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), RESULT);
            }
          return CUP$PeclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // exLogicas ::= logica 
            {
              Object RESULT =null;
		aux4=new NodoHoja("Log",sif.toString());  
              CUP$PeclCup$result = parser.getSymbolFactory().newSymbol("exLogicas",16, ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), RESULT);
            }
          return CUP$PeclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // logica ::= comparacion 
            {
              Object RESULT =null;

              CUP$PeclCup$result = parser.getSymbolFactory().newSymbol("logica",15, ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), RESULT);
            }
          return CUP$PeclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // logica ::= IDE 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$PeclCup$stack.peek()).value;
		compruebaBool(id, idleft+1); sif.append(id.toString()); 
              CUP$PeclCup$result = parser.getSymbolFactory().newSymbol("logica",15, ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), RESULT);
            }
          return CUP$PeclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // comp ::= DISTINTO 
            {
              Object RESULT =null;
		RESULT=" distinto ";
              CUP$PeclCup$result = parser.getSymbolFactory().newSymbol("comp",11, ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), RESULT);
            }
          return CUP$PeclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // comp ::= MAYOR_IGUAL 
            {
              Object RESULT =null;
		RESULT=" mayor_igual ";
              CUP$PeclCup$result = parser.getSymbolFactory().newSymbol("comp",11, ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), RESULT);
            }
          return CUP$PeclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // comp ::= MAYOR 
            {
              Object RESULT =null;
		RESULT=" mayor ";
              CUP$PeclCup$result = parser.getSymbolFactory().newSymbol("comp",11, ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), RESULT);
            }
          return CUP$PeclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // comp ::= IGUAL 
            {
              Object RESULT =null;
		RESULT=" igual ";
              CUP$PeclCup$result = parser.getSymbolFactory().newSymbol("comp",11, ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), RESULT);
            }
          return CUP$PeclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // comp ::= MENOR 
            {
              Object RESULT =null;
		RESULT=" menor ";
              CUP$PeclCup$result = parser.getSymbolFactory().newSymbol("comp",11, ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), RESULT);
            }
          return CUP$PeclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // comp ::= MENOR_IGUAL 
            {
              Object RESULT =null;
		RESULT=" menor_igual ";
              CUP$PeclCup$result = parser.getSymbolFactory().newSymbol("comp",11, ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), RESULT);
            }
          return CUP$PeclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // comparacion ::= error 
            {
              Object RESULT =null;
		numErr++;
              CUP$PeclCup$result = parser.getSymbolFactory().newSymbol("comparacion",12, ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), RESULT);
            }
          return CUP$PeclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // comparacion ::= IDE IGUAL tipoBool 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$PeclCup$stack.elementAt(CUP$PeclCup$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$PeclCup$stack.elementAt(CUP$PeclCup$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$PeclCup$stack.elementAt(CUP$PeclCup$top-2)).value;
		int tbleft = ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()).left;
		int tbright = ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()).right;
		Object tb = (Object)((java_cup.runtime.Symbol) CUP$PeclCup$stack.peek()).value;
		compruebaVariable(id,"boolean", idleft+1); sif.append(id.toString()); sif.append(" igual "); sif.append(tb);
              CUP$PeclCup$result = parser.getSymbolFactory().newSymbol("comparacion",12, ((java_cup.runtime.Symbol)CUP$PeclCup$stack.elementAt(CUP$PeclCup$top-2)), ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), RESULT);
            }
          return CUP$PeclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // comparacion ::= IDE comp numero 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$PeclCup$stack.elementAt(CUP$PeclCup$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$PeclCup$stack.elementAt(CUP$PeclCup$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$PeclCup$stack.elementAt(CUP$PeclCup$top-2)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$PeclCup$stack.elementAt(CUP$PeclCup$top-1)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$PeclCup$stack.elementAt(CUP$PeclCup$top-1)).right;
		Object c = (Object)((java_cup.runtime.Symbol) CUP$PeclCup$stack.elementAt(CUP$PeclCup$top-1)).value;
		int nleft = ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()).right;
		Object n = (Object)((java_cup.runtime.Symbol) CUP$PeclCup$stack.peek()).value;
		compruebaVariable(id,"integer", idleft+1);sif.append(id.toString()); sif.append(c); sif.append(n.toString());
              CUP$PeclCup$result = parser.getSymbolFactory().newSymbol("comparacion",12, ((java_cup.runtime.Symbol)CUP$PeclCup$stack.elementAt(CUP$PeclCup$top-2)), ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), RESULT);
            }
          return CUP$PeclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // comparacion ::= IDE comp IDE 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$PeclCup$stack.elementAt(CUP$PeclCup$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$PeclCup$stack.elementAt(CUP$PeclCup$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$PeclCup$stack.elementAt(CUP$PeclCup$top-2)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$PeclCup$stack.elementAt(CUP$PeclCup$top-1)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$PeclCup$stack.elementAt(CUP$PeclCup$top-1)).right;
		Object c = (Object)((java_cup.runtime.Symbol) CUP$PeclCup$stack.elementAt(CUP$PeclCup$top-1)).value;
		int id2left = ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()).left;
		int id2right = ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()).right;
		String id2 = (String)((java_cup.runtime.Symbol) CUP$PeclCup$stack.peek()).value;
		compruebaVariable(id, id2, idleft+1); sif.append(id.toString()); sif.append(c.toString()); sif.append(id2.toString());
              CUP$PeclCup$result = parser.getSymbolFactory().newSymbol("comparacion",12, ((java_cup.runtime.Symbol)CUP$PeclCup$stack.elementAt(CUP$PeclCup$top-2)), ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), RESULT);
            }
          return CUP$PeclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // tipoBool ::= NOT PARENT_IZQ logica PARENT_DER 
            {
              Object RESULT =null;
		RESULT="NEGADA";
              CUP$PeclCup$result = parser.getSymbolFactory().newSymbol("tipoBool",10, ((java_cup.runtime.Symbol)CUP$PeclCup$stack.elementAt(CUP$PeclCup$top-3)), ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), RESULT);
            }
          return CUP$PeclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // tipoBool ::= FALSE 
            {
              Object RESULT =null;
		RESULT="FALSE"; 
              CUP$PeclCup$result = parser.getSymbolFactory().newSymbol("tipoBool",10, ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), RESULT);
            }
          return CUP$PeclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // tipoBool ::= TRUE 
            {
              Object RESULT =null;
		RESULT="TRUE"; 
              CUP$PeclCup$result = parser.getSymbolFactory().newSymbol("tipoBool",10, ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), RESULT);
            }
          return CUP$PeclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // tipo ::= tipoBool 
            {
              Object RESULT =null;
		int tbleft = ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()).left;
		int tbright = ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()).right;
		Object tb = (Object)((java_cup.runtime.Symbol) CUP$PeclCup$stack.peek()).value;
		RESULT="boolean"; aux3= new NodoHoja("BOOL",tb.toString());
              CUP$PeclCup$result = parser.getSymbolFactory().newSymbol("tipo",9, ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), RESULT);
            }
          return CUP$PeclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // tipo ::= numero 
            {
              Object RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()).right;
		Object n = (Object)((java_cup.runtime.Symbol) CUP$PeclCup$stack.peek()).value;
		RESULT="integer"; aux3= new NodoHoja("NUM",n.toString()); 
              CUP$PeclCup$result = parser.getSymbolFactory().newSymbol("tipo",9, ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), RESULT);
            }
          return CUP$PeclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // tipo ::= IDE 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$PeclCup$stack.peek()).value;
		 RESULT=id; aux3= new NodoHoja("IDE",id.toString());
              CUP$PeclCup$result = parser.getSymbolFactory().newSymbol("tipo",9, ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), RESULT);
            }
          return CUP$PeclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // asignacion ::= error tipo 
            {
              Object RESULT =null;
		numErr++;
              CUP$PeclCup$result = parser.getSymbolFactory().newSymbol("asignacion",8, ((java_cup.runtime.Symbol)CUP$PeclCup$stack.elementAt(CUP$PeclCup$top-1)), ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), RESULT);
            }
          return CUP$PeclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // asignacion ::= IDE ASIGNACION tipo 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$PeclCup$stack.elementAt(CUP$PeclCup$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$PeclCup$stack.elementAt(CUP$PeclCup$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$PeclCup$stack.elementAt(CUP$PeclCup$top-2)).value;
		int tipleft = ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()).left;
		int tipright = ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()).right;
		Object tip = (Object)((java_cup.runtime.Symbol) CUP$PeclCup$stack.peek()).value;
		compruebaVariableAsig(id, tip, tipleft+1); aux = new NodoIntermedio(id.toString()); aux.añadirHijo(aux3);  
              CUP$PeclCup$result = parser.getSymbolFactory().newSymbol("asignacion",8, ((java_cup.runtime.Symbol)CUP$PeclCup$stack.elementAt(CUP$PeclCup$top-2)), ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), RESULT);
            }
          return CUP$PeclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // expresion ::= expresion2 
            {
              Object RESULT =null;

              CUP$PeclCup$result = parser.getSymbolFactory().newSymbol("expresion",5, ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), RESULT);
            }
          return CUP$PeclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // expresion ::= while 
            {
              Object RESULT =null;
		 aux1=new NodoIntermedio("while"); aux1.añadirHijo(aux); añadeExpresion();
              CUP$PeclCup$result = parser.getSymbolFactory().newSymbol("expresion",5, ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), RESULT);
            }
          return CUP$PeclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // expresion ::= if 
            {
              Object RESULT =null;
		 aux1=new NodoIntermedio("if"); aux1.añadirHijo(aux); añadeExpresion();
              CUP$PeclCup$result = parser.getSymbolFactory().newSymbol("expresion",5, ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), RESULT);
            }
          return CUP$PeclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // expresion ::= asignacion 
            {
              Object RESULT =null;
		 aux1=new NodoIntermedio("Asign"); aux1.añadirHijo(aux); añadeExpresion();
              CUP$PeclCup$result = parser.getSymbolFactory().newSymbol("expresion",5, ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), RESULT);
            }
          return CUP$PeclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // expresion ::= operacion 
            {
              Object RESULT =null;
		 aux1=new NodoIntermedio("Operation"); aux1.añadirHijo(aux); añadeExpresion();
              CUP$PeclCup$result = parser.getSymbolFactory().newSymbol("expresion",5, ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), RESULT);
            }
          return CUP$PeclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // mas ::= 
            {
              Object RESULT =null;

              CUP$PeclCup$result = parser.getSymbolFactory().newSymbol("mas",13, ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), RESULT);
            }
          return CUP$PeclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // mas ::= PUNTO_COMA expresion mas 
            {
              Object RESULT =null;

              CUP$PeclCup$result = parser.getSymbolFactory().newSymbol("mas",13, ((java_cup.runtime.Symbol)CUP$PeclCup$stack.elementAt(CUP$PeclCup$top-2)), ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), RESULT);
            }
          return CUP$PeclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // sentencias ::= 
            {
              Object RESULT =null;

              CUP$PeclCup$result = parser.getSymbolFactory().newSymbol("sentencias",7, ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), RESULT);
            }
          return CUP$PeclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // sentencias ::= expresion mas 
            {
              Object RESULT =null;

              CUP$PeclCup$result = parser.getSymbolFactory().newSymbol("sentencias",7, ((java_cup.runtime.Symbol)CUP$PeclCup$stack.elementAt(CUP$PeclCup$top-1)), ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), RESULT);
            }
          return CUP$PeclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // programa ::= BEGIN sentencias END 
            {
              Object RESULT =null;

              CUP$PeclCup$result = parser.getSymbolFactory().newSymbol("programa",1, ((java_cup.runtime.Symbol)CUP$PeclCup$stack.elementAt(CUP$PeclCup$top-2)), ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), RESULT);
            }
          return CUP$PeclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // var ::= BOOLEAN 
            {
              Object RESULT =null;
		int booleleft = ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()).left;
		int booleright = ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()).right;
		String boole = (String)((java_cup.runtime.Symbol) CUP$PeclCup$stack.peek()).value;
		RESULT=boole.toString();
              CUP$PeclCup$result = parser.getSymbolFactory().newSymbol("var",4, ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), RESULT);
            }
          return CUP$PeclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // var ::= INTEGER 
            {
              Object RESULT =null;
		int inteleft = ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()).left;
		int interight = ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()).right;
		String inte = (String)((java_cup.runtime.Symbol) CUP$PeclCup$stack.peek()).value;
		RESULT=inte.toString();
              CUP$PeclCup$result = parser.getSymbolFactory().newSymbol("var",4, ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), RESULT);
            }
          return CUP$PeclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // enum ::= error 
            {
              Object RESULT =null;
		numErr++;
              CUP$PeclCup$result = parser.getSymbolFactory().newSymbol("enum",6, ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), RESULT);
            }
          return CUP$PeclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // enum ::= enum COMA IDE 
            {
              Object RESULT =null;
		int IDleft = ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()).left;
		int IDright = ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()).right;
		String ID = (String)((java_cup.runtime.Symbol) CUP$PeclCup$stack.peek()).value;
		añadirArray(ID.toString(),IDleft+1);
              CUP$PeclCup$result = parser.getSymbolFactory().newSymbol("enum",6, ((java_cup.runtime.Symbol)CUP$PeclCup$stack.elementAt(CUP$PeclCup$top-2)), ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), RESULT);
            }
          return CUP$PeclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // enum ::= IDE 
            {
              Object RESULT =null;
		int IDleft = ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()).left;
		int IDright = ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()).right;
		String ID = (String)((java_cup.runtime.Symbol) CUP$PeclCup$stack.peek()).value;
		añadirArray(ID.toString(),IDleft+1); 
              CUP$PeclCup$result = parser.getSymbolFactory().newSymbol("enum",6, ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), RESULT);
            }
          return CUP$PeclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // variable ::= error 
            {
              Object RESULT =null;
		numErr++;
              CUP$PeclCup$result = parser.getSymbolFactory().newSymbol("variable",3, ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), RESULT);
            }
          return CUP$PeclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // variable ::= VAR enum PUNTO_COMA 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$PeclCup$stack.elementAt(CUP$PeclCup$top-2)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$PeclCup$stack.elementAt(CUP$PeclCup$top-2)).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$PeclCup$stack.elementAt(CUP$PeclCup$top-2)).value;
		aux = new NodoIntermedio("undefined"); añadeHojaDecl(); añadirVariablesUnd(eleft+1);  
              CUP$PeclCup$result = parser.getSymbolFactory().newSymbol("variable",3, ((java_cup.runtime.Symbol)CUP$PeclCup$stack.elementAt(CUP$PeclCup$top-2)), ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), RESULT);
            }
          return CUP$PeclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // variable ::= VAR enum DOS_PUNTOS var PUNTO_COMA 
            {
              Object RESULT =null;
		int variableleft = ((java_cup.runtime.Symbol)CUP$PeclCup$stack.elementAt(CUP$PeclCup$top-1)).left;
		int variableright = ((java_cup.runtime.Symbol)CUP$PeclCup$stack.elementAt(CUP$PeclCup$top-1)).right;
		Object variable = (Object)((java_cup.runtime.Symbol) CUP$PeclCup$stack.elementAt(CUP$PeclCup$top-1)).value;
		aux = new NodoIntermedio(variable.toString());  añadeHojaDecl();  añadirVariables(variable, variableleft+1);
              CUP$PeclCup$result = parser.getSymbolFactory().newSymbol("variable",3, ((java_cup.runtime.Symbol)CUP$PeclCup$stack.elementAt(CUP$PeclCup$top-4)), ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), RESULT);
            }
          return CUP$PeclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // variables ::= 
            {
              Object RESULT =null;

              CUP$PeclCup$result = parser.getSymbolFactory().newSymbol("variables",2, ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), RESULT);
            }
          return CUP$PeclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // variables ::= variables variable 
            {
              Object RESULT =null;
		aux1=new NodoIntermedio("Decl"); aux1.añadirHijo(aux); raiz.añadirHijo(aux1); 
              CUP$PeclCup$result = parser.getSymbolFactory().newSymbol("variables",2, ((java_cup.runtime.Symbol)CUP$PeclCup$stack.elementAt(CUP$PeclCup$top-1)), ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), RESULT);
            }
          return CUP$PeclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // nombreProg ::= IDE 
            {
              Object RESULT =null;
		int NOMBREleft = ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()).left;
		int NOMBREright = ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()).right;
		String NOMBRE = (String)((java_cup.runtime.Symbol) CUP$PeclCup$stack.peek()).value;
		 tSimbolos.put(NOMBRE.toString(), new Simbolo("pseudo")); raiz = new NodoRaiz();  a= new Arbol(raiz);
              CUP$PeclCup$result = parser.getSymbolFactory().newSymbol("nombreProg",35, ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), RESULT);
            }
          return CUP$PeclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // inicio ::= PROGRAM nombreProg IS variables programa 
            {
              Object RESULT =null;
		 fin(); 
              CUP$PeclCup$result = parser.getSymbolFactory().newSymbol("inicio",0, ((java_cup.runtime.Symbol)CUP$PeclCup$stack.elementAt(CUP$PeclCup$top-4)), ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), RESULT);
            }
          return CUP$PeclCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= inicio EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$PeclCup$stack.elementAt(CUP$PeclCup$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$PeclCup$stack.elementAt(CUP$PeclCup$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$PeclCup$stack.elementAt(CUP$PeclCup$top-1)).value;
		RESULT = start_val;
              CUP$PeclCup$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$PeclCup$stack.elementAt(CUP$PeclCup$top-1)), ((java_cup.runtime.Symbol)CUP$PeclCup$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$PeclCup$parser.done_parsing();
          return CUP$PeclCup$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

