/* The following code was generated by JFlex 1.4.3 on 28/11/17 20:01 */

package pecl;


import java.util.*;
import java.io.*;
import java_cup.runtime.*;
//Bloque de configuracion analizador

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 28/11/17 20:01 from the specification file
 * <tt>E:/UNI/PROCESADORES/CUPProject/CUPProject/src/pecl/pecl.lex</tt>
 */
class Yylex implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = {
     0,  0,  0,  0,  0,  0,  0,  0,  0, 37, 39,  0,  0, 38,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     4,  0,  0,  0,  0,  0,  0,  0, 33, 34, 31, 29, 35, 30,  4, 32, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 25, 36, 27, 26, 28,  0, 
     0,  9, 13,  2, 16, 14, 23,  8, 22, 11,  2, 21, 19, 10, 15,  7, 
     5,  2,  6, 12, 18, 24, 17, 20,  2,  2,  2,  0,  0,  0,  0,  3, 
     0,  9, 13,  2, 16, 14, 23,  8, 22, 11,  2, 21, 19, 10, 15,  7, 
     5,  2,  6, 12, 18, 24, 17, 20,  2,  2,  2,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0
  };

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\1\1\2\1\3\1\1\1\4\16\3\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\2\4\1\1\2\3\1\21\1\3\1\22"+
    "\1\3\1\23\6\3\1\24\6\3\1\25\1\26\1\27"+
    "\1\30\2\3\1\31\4\3\1\32\1\3\1\33\1\34"+
    "\6\3\1\35\1\3\1\36\2\3\1\37\1\40\1\41"+
    "\6\3\1\42\1\43\1\44\1\45\3\3\1\46\1\47"+
    "\1\50";

  private static int [] zzUnpackAction() {
    int [] result = new int[100];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\50\0\120\0\170\0\240\0\310\0\360\0\u0118"+
    "\0\u0140\0\u0168\0\u0190\0\u01b8\0\u01e0\0\u0208\0\u0230\0\u0258"+
    "\0\u0280\0\u02a8\0\u02d0\0\u02f8\0\u0320\0\310\0\u0348\0\u0370"+
    "\0\310\0\310\0\310\0\310\0\310\0\310\0\310\0\310"+
    "\0\u0398\0\u03c0\0\u03e8\0\u0410\0\u0438\0\170\0\u0460\0\170"+
    "\0\u0488\0\170\0\u04b0\0\u04d8\0\u0500\0\u0528\0\u0550\0\u0578"+
    "\0\170\0\u05a0\0\u05c8\0\u05f0\0\u0618\0\u0640\0\u0668\0\310"+
    "\0\310\0\310\0\310\0\u0690\0\u06b8\0\170\0\u06e0\0\u0708"+
    "\0\u0730\0\u0758\0\170\0\u0780\0\170\0\170\0\u07a8\0\u07d0"+
    "\0\u07f8\0\u0820\0\u0848\0\u0870\0\170\0\u0898\0\170\0\u08c0"+
    "\0\u08e8\0\170\0\170\0\170\0\u0910\0\u0938\0\u0960\0\u0988"+
    "\0\u09b0\0\u09d8\0\170\0\170\0\170\0\170\0\u0a00\0\u0a28"+
    "\0\u0a50\0\170\0\170\0\170";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[100];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\4\1\12\1\4\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\1\4\1\23\2\4\1\24\1\4"+
    "\1\25\1\26\1\27\1\30\1\31\1\32\1\33\1\34"+
    "\1\35\1\36\1\37\1\40\1\41\1\42\1\6\1\2"+
    "\3\43\1\0\24\43\17\0\1\2\1\3\2\5\1\0"+
    "\24\5\17\0\1\2\3\4\1\0\24\4\17\0\1\2"+
    "\3\5\1\0\24\5\67\0\1\2\3\4\1\0\1\4"+
    "\1\44\22\4\17\0\1\2\3\4\1\0\11\4\1\45"+
    "\12\4\17\0\1\2\3\4\1\0\1\4\1\46\22\4"+
    "\17\0\1\2\3\4\1\0\12\4\1\47\11\4\17\0"+
    "\1\2\3\4\1\0\7\4\1\50\2\4\1\51\7\4"+
    "\1\52\1\4\17\0\1\2\3\4\1\0\20\4\1\53"+
    "\3\4\17\0\1\2\3\4\1\0\2\4\1\54\6\4"+
    "\1\55\12\4\17\0\1\2\3\4\1\0\12\4\1\56"+
    "\3\4\1\57\5\4\17\0\1\2\3\4\1\0\2\4"+
    "\1\60\21\4\17\0\1\2\3\4\1\0\2\4\1\61"+
    "\21\4\17\0\1\2\3\4\1\0\4\4\1\62\17\4"+
    "\17\0\1\2\3\4\1\0\1\4\1\63\17\4\1\64"+
    "\2\4\17\0\1\2\3\4\1\0\1\4\1\65\17\4"+
    "\1\66\2\4\17\0\1\2\3\4\1\0\4\4\1\67"+
    "\17\4\51\0\1\70\47\0\1\71\1\0\1\72\45\0"+
    "\1\73\63\0\1\6\50\0\1\6\1\0\3\43\1\0"+
    "\24\43\17\0\1\2\3\4\1\0\2\4\1\74\21\4"+
    "\17\0\1\2\3\4\1\0\4\4\1\75\17\4\17\0"+
    "\1\2\3\4\1\0\13\4\1\76\10\4\17\0\1\2"+
    "\3\4\1\0\15\4\1\77\6\4\17\0\1\2\3\4"+
    "\1\0\6\4\1\100\15\4\17\0\1\2\3\4\1\0"+
    "\2\4\1\101\21\4\17\0\1\2\3\4\1\0\3\4"+
    "\1\102\20\4\17\0\1\2\3\4\1\0\13\4\1\103"+
    "\10\4\17\0\1\2\3\4\1\0\7\4\1\104\14\4"+
    "\17\0\1\2\3\4\1\0\15\4\1\105\6\4\17\0"+
    "\1\2\3\4\1\0\1\4\1\106\22\4\17\0\1\2"+
    "\3\4\1\0\23\4\1\107\17\0\1\2\3\4\1\0"+
    "\11\4\1\110\12\4\17\0\1\2\3\4\1\0\6\4"+
    "\1\111\15\4\17\0\1\2\3\4\1\0\6\4\1\112"+
    "\15\4\17\0\1\2\3\4\1\0\16\4\1\113\5\4"+
    "\17\0\1\2\3\4\1\0\3\4\1\114\20\4\17\0"+
    "\1\2\3\4\1\0\13\4\1\115\10\4\17\0\1\2"+
    "\3\4\1\0\11\4\1\116\12\4\17\0\1\2\3\4"+
    "\1\0\1\117\23\4\17\0\1\2\3\4\1\0\16\4"+
    "\1\120\5\4\17\0\1\2\3\4\1\0\6\4\1\121"+
    "\15\4\17\0\1\2\3\4\1\0\11\4\1\122\12\4"+
    "\17\0\1\2\3\4\1\0\11\4\1\123\12\4\17\0"+
    "\1\2\3\4\1\0\12\4\1\124\11\4\17\0\1\2"+
    "\3\4\1\0\15\4\1\125\6\4\17\0\1\2\3\4"+
    "\1\0\16\4\1\126\5\4\17\0\1\2\3\4\1\0"+
    "\7\4\1\127\14\4\17\0\1\2\3\4\1\0\1\4"+
    "\1\130\22\4\17\0\1\2\3\4\1\0\3\4\1\131"+
    "\20\4\17\0\1\2\3\4\1\0\11\4\1\132\12\4"+
    "\17\0\1\2\3\4\1\0\12\4\1\133\11\4\17\0"+
    "\1\2\3\4\1\0\11\4\1\134\12\4\17\0\1\2"+
    "\3\4\1\0\11\4\1\135\12\4\17\0\1\2\3\4"+
    "\1\0\11\4\1\136\12\4\17\0\1\2\3\4\1\0"+
    "\4\4\1\137\17\4\17\0\1\2\3\4\1\0\11\4"+
    "\1\140\12\4\17\0\1\2\3\4\1\0\4\4\1\141"+
    "\17\4\17\0\1\2\3\4\1\0\5\4\1\142\16\4"+
    "\17\0\1\2\3\4\1\0\1\4\1\143\22\4\17\0"+
    "\1\2\3\4\1\0\12\4\1\144\11\4\17\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2680];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\5\1\1\11\17\1\1\11\2\1\10\11\27\1\4\11"+
    "\51\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[100];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */

private ArrayList<String> tokens = new ArrayList<>();
int err=0;
public int getErr(){
	return err;
}
public String imprimir() throws IOException {
	String s="\n[";
	Iterator<String> itr = tokens.iterator();
	int cont=0;
	while (itr.hasNext()) {
		cont++;
		s=s+itr.next();
		if(itr.hasNext()){
			s=s+", ";
			if(cont%5==0){
				s=s+"\n";
			}
		}
	}
	s=s+"]";
	return s;
}


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Yylex(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Yylex(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 3: 
          { this.tokens.add("ide "+ "("+yytext()+")"); return new Symbol(PeclSym.IDE, yyline, yycolumn, yytext());
          }
        case 41: break;
        case 20: 
          { this.tokens.add(yytext()); return new Symbol(PeclSym.DO, yyline, yycolumn, yytext());
          }
        case 42: break;
        case 11: 
          { this.tokens.add("mul"); return new Symbol(PeclSym.MULTIPLICACION, yyline, yycolumn, yytext());
          }
        case 43: break;
        case 36: 
          { this.tokens.add(yytext()); return new Symbol(PeclSym.WHILE, yyline, yycolumn, yytext());
          }
        case 44: break;
        case 30: 
          { this.tokens.add(yytext()); return new Symbol(PeclSym.SKIP, yyline, yycolumn, yytext());
          }
        case 45: break;
        case 19: 
          { this.tokens.add(yytext()); return new Symbol(PeclSym.IF, yyline, yycolumn, yytext());
          }
        case 46: break;
        case 34: 
          { this.tokens.add(yytext()); return new Symbol(PeclSym.BEGIN, yyline, yycolumn, yytext());
          }
        case 47: break;
        case 7: 
          { this.tokens.add("comp"); return new Symbol(PeclSym.MENOR, yyline, yycolumn, yytext());
          }
        case 48: break;
        case 29: 
          { this.tokens.add(yytext()); return new Symbol(PeclSym.READ, yyline, yycolumn, yytext());
          }
        case 49: break;
        case 22: 
          { this.tokens.add("comp"); return new Symbol(PeclSym.MENOR_IGUAL, yyline, yycolumn, yytext());
          }
        case 50: break;
        case 31: 
          { this.tokens.add(yytext()); return new Symbol(PeclSym.ELSE, yyline, yycolumn, yytext());
          }
        case 51: break;
        case 35: 
          { this.tokens.add(yytext()); return new Symbol(PeclSym.WRITE, yyline, yycolumn, yytext());
          }
        case 52: break;
        case 15: 
          { this.tokens.add("coma"); return new Symbol(PeclSym.COMA, yyline, yycolumn, yytext());
          }
        case 53: break;
        case 5: 
          { this.tokens.add("dos_puntos"); return new Symbol(PeclSym.DOS_PUNTOS, yyline, yycolumn, yytext());
          }
        case 54: break;
        case 26: 
          { this.tokens.add(yytext()); return new Symbol(PeclSym.END, yyline, yycolumn, yytext());
          }
        case 55: break;
        case 18: 
          { this.tokens.add(yytext()); return new Symbol(PeclSym.IS, yyline, yycolumn, yytext());
          }
        case 56: break;
        case 8: 
          { this.tokens.add("comp"); return new Symbol(PeclSym.MAYOR, yyline, yycolumn, yytext());
          }
        case 57: break;
        case 16: 
          { this.tokens.add("punto_coma"); return new Symbol(PeclSym.PUNTO_COMA, yyline, yycolumn, yytext());
          }
        case 58: break;
        case 9: 
          { this.tokens.add("mas"); return new Symbol(PeclSym.SUMA, yyline, yycolumn, yytext());
          }
        case 59: break;
        case 27: 
          { this.tokens.add(yytext()); return new Symbol(PeclSym.NOT, yyline, yycolumn, yytext());
          }
        case 60: break;
        case 10: 
          { this.tokens.add("menos"); return new Symbol(PeclSym.RESTA, yyline, yycolumn, yytext());
          }
        case 61: break;
        case 28: 
          { this.tokens.add(yytext()); return new Symbol(PeclSym.VAR, yyline, yycolumn, yytext());
          }
        case 62: break;
        case 2: 
          { this.tokens.add("num "+ "("+yytext()+")"); return new Symbol(PeclSym.NUM, yyline, yycolumn, yytext());
          }
        case 63: break;
        case 23: 
          { this.tokens.add("comp"); return new Symbol(PeclSym.DISTINTO, yyline, yycolumn, yytext());
          }
        case 64: break;
        case 21: 
          { this.tokens.add("asign"); return new Symbol(PeclSym.ASIGNACION, yyline, yycolumn, yytext());
          }
        case 65: break;
        case 12: 
          { this.tokens.add("div"); return new Symbol(PeclSym.DIVISION, yyline, yycolumn, yytext());
          }
        case 66: break;
        case 1: 
          { System.err.println("Asignador incorrecto en linea: "+ (yyline+1)+ " columna:"+(yycolumn+1) +" Carácter: "+yytext() );System.out.println();err++;
          }
        case 67: break;
        case 33: 
          { this.tokens.add(yytext()); return new Symbol(PeclSym.THEN, yyline, yycolumn, yytext());
          }
        case 68: break;
        case 38: 
          { this.tokens.add(yytext()); return new Symbol(PeclSym.PROGRAM, yyline, yycolumn, yytext());
          }
        case 69: break;
        case 40: 
          { this.tokens.add(yytext()); return new Symbol(PeclSym.BOOLEAN, yyline, yycolumn, yytext());
          }
        case 70: break;
        case 25: 
          { this.tokens.add(yytext()); return new Symbol(PeclSym.AND, yyline, yycolumn, yytext());
          }
        case 71: break;
        case 37: 
          { this.tokens.add(yytext()); return new Symbol(PeclSym.FALSE, yyline, yycolumn, yytext());
          }
        case 72: break;
        case 39: 
          { this.tokens.add(yytext()); return new Symbol(PeclSym.INTEGER, yyline, yycolumn, yytext());
          }
        case 73: break;
        case 17: 
          { this.tokens.add(yytext()); return new Symbol(PeclSym.OR, yyline, yycolumn, yytext());
          }
        case 74: break;
        case 13: 
          { this.tokens.add("paren_izq"); return new Symbol(PeclSym.PARENT_IZQ, yyline, yycolumn, yytext());
          }
        case 75: break;
        case 14: 
          { this.tokens.add("paren_der"); return new Symbol(PeclSym.PARENT_DER, yyline, yycolumn, yytext());
          }
        case 76: break;
        case 24: 
          { this.tokens.add("comp"); return new Symbol(PeclSym.MAYOR_IGUAL, yyline, yycolumn, yytext());
          }
        case 77: break;
        case 6: 
          { this.tokens.add("comp"); return new Symbol(PeclSym.IGUAL, yyline, yycolumn, yytext());
          }
        case 78: break;
        case 32: 
          { this.tokens.add(yytext()); return new Symbol(PeclSym.TRUE, yyline, yycolumn, yytext());
          }
        case 79: break;
        case 4: 
          { 
          }
        case 80: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              {
                return new Symbol(PeclSym.EOF);
              }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
